name: nekos_best
description: A dart package for interacting with nekos.best api. Easy and simple package to make requests to nekos.best and fetch results.
version: 2.1.2
homepage: https://github.com/Yakiyo/nekos_best_dart
repository: https://github.com/Yakiyo/nekos_best_dart

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  http: ^0.13.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
